orders:
  function: orders/index.js
  web: yes
  runtime: nodejs:20
  inputs:
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRETS: $OAUTH_CLIENT_SECRETS
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_SCOPES: $OAUTH_SCOPES
    OAUTH_IMS_ORG_ID: $OAUTH_IMS_ORG_ID
    LOG_LEVEL: debug
run-action:
  function: run-action/index.js
  web: yes
  runtime: nodejs:20
  inputs:
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRETS: $OAUTH_CLIENT_SECRETS
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_SCOPES: $OAUTH_SCOPES
    OAUTH_IMS_ORG_ID: $OAUTH_IMS_ORG_ID
    LOG_LEVEL: debug
